<?php
$l['number'] 						= 'Reference';
$l['date'] 							= 'Billing date';
$l['due'] 							= 'Due date';
$l['to'] 							= 'Billing to';
$l['from'] 							= 'Our information';
$l['product'] 						= 'Product';
$l['amount'] 						= 'Amount';
$l['price'] 						= 'Price';
$l['discount'] 						= 'Discount';
$l['vat'] 							= 'Vat';
$l['total'] 						= 'Total';
$l['page'] 							= 'Page';
$l['page_of'] 						= 'of';
$l['qty'] 						= 'qty';
$l['unitprice'] 						= 'unit order value';
$l['ordervalue'] 						= 'total order value';
$l['taxvalue'] 						= 'Tax Value';
$l['totalval'] 						= 'total order value incl tax';
?>